/* eslint-disable prettier/prettier */
// LOGIN //
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// GET_ALL_MEATS //
export const GET_ALL_MEATS_REQUEST = 'GET_ALL_MEATS_REQUEST'
export const GET_ALL_MEATS_SUCCESS = 'GET_ALL_MEATS_SUCCESS'
export const GET_ALL_MEATS_FAILURE = 'GET_ALL_MEATS_FAILURE'